name: Deploy VitePress site to GitHub Pages

on:
  push:
    branches:
      - main # 当你推送或合并到 main 时自动部署

permissions:
  contents: write # 允许推送到 gh-pages 分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 设置 pnpm（识别 pnpm-lock.yaml）
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9 # 请与你本地版本一致

      # 设置 Node.js 版本
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # 安装依赖
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 构建 VitePress 静态文件
      - name: Build site
        run: pnpm run docs:build

      # 部署到 gh-pages 分支
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
          publish_branch: gh-pages
